##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: A Snapshot of Texas Business History
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Digital Libraries 2025 Project
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This digital collection features oral histories collected by Dr. Floyd Jenkins, a business professor, as a part of the Business Archives Project at North Texas State University, now called the University of North Texas. These oral history interviews document the everyday operations, labor practices, customer relations, and lives of small Texas business owners from the 1890s to the 1970s. These business owners’ firsthand accounts offer valuable insight into these businesses adapted to economic shifts and technological change. The collection serves as a relevant primary source for studying regional history, labor practices, entrepreneurship, and technological innovation of small businesses. From the stories of bakery owners Anne and Don Davis to those of auto mechanic and entrepreneur Ned Estes, we can gain perspectives on what historians and archivists called the quotidian, or the everyday. The scholar Liz Stanley refers to the quotidian as “the everyday and seemingly mundane and commonplace - is at one and the same time both ordinary and extraordinary. and has both ‘small’ and ‘big’ story attributes.” These stories aren’t talking about famous figures in history, but rather normal, working people living through historical events. This oral history collection fills an important gap in digital archives by centering the lived experiences of family-owned business owners in small towns in Texas rather than centering big business operations in metropolitan centers. While these stories are certainly overlooked, a glaring omission from these histories is the stories and contributions of workers, women, and people of color, which contributes to the narrative that these white, male business owners are the “representative” leaders of their communities. Stanley, Liz (2010) On Small and Big Stories of the Quotidian: The Commonplace and the Extraordinary in Narrative Inquiry. In: Narrative, Memory and Ordinary Lives. University of Huddersfield, Huddersfield, pp. 1-24. ISBN 978-1-86218-090-1 "
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: CollectionBuilder

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: cbmetadataupdated16

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

# _config.yml
plugins:
  - jekyll-emoji
gems:
  - jekyll-emoji

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
